package dev.y.works.iconescatolicosonline.domain.encomenda;

public enum StatusEncomenda {
    ENCOMENDA_CRIADA,
    AGUARDANDO_PAGAMENTO_INICIAL,
    PAGAMENTO_INICIAL_CONFIRMADO,
    PRODUCAO_LIBERADA,
    EM_PRODUCAO,
    EM_ACABAMENTO,
    PRONTO_PARA_ENTREGA_RETIRADA,
    AGUARDANDO_PAGAMENTO_RESTANTE,
    ENVIADO_OU_RETIRADO,
    CONCLUIDO,
    CANCELADO
}
