package dev.y.works.iconescatolicosonline.service.carrinho;
import dev.y.works.iconescatolicosonline.domain.carrinho.ItemCarrinho; import dev.y.works.iconescatolicosonline.dto.carrinho.*; import dev.y.works.iconescatolicosonline.dto.encomenda.PersonalizacaoResponse; import dev.y.works.iconescatolicosonline.exception.RecursoNaoEncontradoException; import dev.y.works.iconescatolicosonline.repository.carrinho.ItemCarrinhoRepository; import dev.y.works.iconescatolicosonline.repository.catalogo.ModeloIconeRepository; import dev.y.works.iconescatolicosonline.repository.usuario.UsuarioRepository; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.List;
@Service public class CarrinhoService {
 private final ItemCarrinhoRepository repository;private final UsuarioRepository usuarioRepository;private final ModeloIconeRepository modeloRepository;
 public CarrinhoService(ItemCarrinhoRepository repository,UsuarioRepository usuarioRepository,ModeloIconeRepository modeloRepository){this.repository=repository;this.usuarioRepository=usuarioRepository;this.modeloRepository=modeloRepository;}
 @Transactional(readOnly=true) public List<ItemCarrinhoResponse> listar(String email){return repository.findByUsuario_EmailIgnoreCaseOrderByCriadoEmAsc(email).stream().map(this::mapear).toList();}
 @Transactional public ItemCarrinhoResponse adicionar(String email,AdicionarItemCarrinhoRequest r){var usuario=usuarioRepository.findByEmailIgnoreCase(email).orElseThrow(()->new RecursoNaoEncontradoException("Usuário não encontrado."));var modelo=modeloRepository.findByIdAndAtivoTrue(r.modeloIconeId()).orElseThrow(()->new RecursoNaoEncontradoException("Modelo de ícone não encontrado ou inativo."));var p=r.personalizacao();var item=new ItemCarrinho();item.setUsuario(usuario);item.setModeloIcone(modelo);item.setQuantidade(r.quantidade());item.setTamanho(p.tamanho());item.setAcabamento(normalizar(p.acabamento()));item.setFrase(normalizar(p.frase()));item.setNomeFamilia(normalizar(p.nomeFamilia()));item.setObservacoes(normalizar(p.observacoes()));return mapear(repository.save(item));}
 @Transactional public ItemCarrinhoResponse quantidade(String email,Long id,int quantidade){var item=buscar(email,id);item.setQuantidade(quantidade);return mapear(repository.save(item));}
 @Transactional public void remover(String email,Long id){repository.delete(buscar(email,id));}
 @Transactional public void limpar(String email){repository.deleteByUsuario_EmailIgnoreCase(email);}
 private ItemCarrinho buscar(String email,Long id){return repository.findByIdAndUsuario_EmailIgnoreCase(id,email).orElseThrow(()->new RecursoNaoEncontradoException("Item do carrinho não encontrado."));}
 private String normalizar(String s){return s==null||s.isBlank()?null:s.trim();}
 private ItemCarrinhoResponse mapear(ItemCarrinho i){return new ItemCarrinhoResponse(i.getId(),i.getModeloIcone().getId(),i.getModeloIcone().getNome(),i.getModeloIcone().getImagemUrl(),i.getModeloIcone().getPrecoBase(),i.getQuantidade(),new PersonalizacaoResponse(i.getTamanho(),i.getAcabamento(),i.getFrase(),i.getNomeFamilia(),i.getObservacoes()));}
}
