CREATE TABLE endereco_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES cliente(id) ON DELETE CASCADE,
    apelido VARCHAR(60) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    logradouro VARCHAR(150) NOT NULL,
    numero_endereco VARCHAR(20) NOT NULL,
    complemento VARCHAR(100),
    bairro VARCHAR(100) NOT NULL,
    cidade VARCHAR(100) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO endereco_cliente (cliente_id, apelido, cep, logradouro, numero_endereco, complemento, bairro, cidade, uf, principal)
SELECT id, 'Principal', cep, logradouro, numero_endereco, complemento, bairro, cidade, uf, TRUE
FROM cliente
WHERE cep IS NOT NULL AND logradouro IS NOT NULL AND numero_endereco IS NOT NULL
  AND bairro IS NOT NULL AND cidade IS NOT NULL AND uf IS NOT NULL;

CREATE INDEX idx_endereco_cliente_cliente ON endereco_cliente(cliente_id);
CREATE UNIQUE INDEX idx_endereco_cliente_principal
    ON endereco_cliente(cliente_id) WHERE principal = TRUE;

ALTER TABLE cliente DROP COLUMN cep;
ALTER TABLE cliente DROP COLUMN logradouro;
ALTER TABLE cliente DROP COLUMN numero_endereco;
ALTER TABLE cliente DROP COLUMN complemento;
ALTER TABLE cliente DROP COLUMN bairro;
ALTER TABLE cliente DROP COLUMN cidade;
ALTER TABLE cliente DROP COLUMN uf;
