CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(30) NOT NULL CHECK (perfil IN ('CLIENTE', 'ADMINISTRADOR')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuario(id),
    telefone VARCHAR(20),
    cpf VARCHAR(14) UNIQUE,
    endereco TEXT
);

CREATE TABLE administrador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuario(id),
    cargo VARCHAR(80) NOT NULL,
    nivel_acesso VARCHAR(40) NOT NULL DEFAULT 'TOTAL'
);

CREATE TABLE modelo_icone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    descricao TEXT NOT NULL,
    imagem_url TEXT,
    preco_base NUMERIC(10,2) NOT NULL CHECK (preco_base >= 0),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conteudo_devocional (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo_icone_id BIGINT NOT NULL UNIQUE REFERENCES modelo_icone(id) ON DELETE CASCADE,
    historia TEXT,
    significado TEXT,
    simbologia TEXT,
    oracao TEXT,
    ocasiao_presente TEXT,
    cuidados TEXT
);

CREATE TABLE encomenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES cliente(id),
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status_encomenda VARCHAR(50) NOT NULL CHECK (status_encomenda IN (
        'ENCOMENDA_CRIADA',
        'AGUARDANDO_PAGAMENTO_SINAL',
        'SINAL_PAGO',
        'PRODUCAO_LIBERADA',
        'EM_PRODUCAO',
        'EM_ACABAMENTO',
        'PRONTO_PARA_ENTREGA_RETIRADA',
        'AGUARDANDO_PAGAMENTO_RESTANTE',
        'ENVIADO_OU_RETIRADO',
        'CONCLUIDO',
        'CANCELADO'
    )),
    status_financeiro VARCHAR(50) NOT NULL CHECK (status_financeiro IN (
        'AGUARDANDO_SINAL',
        'SINAL_PAGO',
        'PAGAMENTO_PARCIAL',
        'AGUARDANDO_RESTANTE',
        'PAGO_INTEGRALMENTE',
        'CANCELADO',
        'REEMBOLSADO'
    )),
    valor_total NUMERIC(10,2) NOT NULL CHECK (valor_total >= 0),
    valor_sinal NUMERIC(10,2) NOT NULL CHECK (valor_sinal >= 0),
    tipo_entrega VARCHAR(20) NOT NULL CHECK (tipo_entrega IN ('ENTREGA', 'RETIRADA')),
    endereco_entrega TEXT,
    observacoes TEXT,
    CHECK (valor_sinal <= valor_total),
    CHECK (tipo_entrega = 'RETIRADA' OR endereco_entrega IS NOT NULL)
);

CREATE TABLE item_encomenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encomenda_id BIGINT NOT NULL REFERENCES encomenda(id) ON DELETE CASCADE,
    modelo_icone_id BIGINT NOT NULL REFERENCES modelo_icone(id),
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    valor_unitario NUMERIC(10,2) NOT NULL CHECK (valor_unitario >= 0)
);

CREATE TABLE personalizacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_encomenda_id BIGINT NOT NULL UNIQUE REFERENCES item_encomenda(id) ON DELETE CASCADE,
    tamanho VARCHAR(50),
    acabamento VARCHAR(80),
    frase VARCHAR(255),
    nome_familia VARCHAR(120),
    observacoes TEXT
);

CREATE TABLE pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encomenda_id BIGINT NOT NULL REFERENCES encomenda(id),
    tipo VARCHAR(40) NOT NULL CHECK (tipo IN ('SINAL', 'RESTANTE', 'INTEGRAL')),
    valor NUMERIC(10,2) NOT NULL CHECK (valor > 0),
    data_pagamento TIMESTAMPTZ,
    status VARCHAR(40) NOT NULL CHECK (status IN ('PENDENTE', 'CONFIRMADO', 'CANCELADO', 'REEMBOLSADO')),
    referencia_simulada VARCHAR(100),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE icone_pronto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo_icone_id BIGINT NOT NULL REFERENCES modelo_icone(id),
    encomenda_id BIGINT UNIQUE REFERENCES encomenda(id),
    tamanho VARCHAR(50) NOT NULL,
    acabamento VARCHAR(80) NOT NULL,
    custo_producao NUMERIC(10,2) NOT NULL CHECK (custo_producao >= 0),
    preco_sugerido NUMERIC(10,2) CHECK (preco_sugerido >= 0),
    status VARCHAR(40) NOT NULL CHECK (status IN ('DISPONIVEL', 'RESERVADO', 'EM_ACABAMENTO', 'VENDIDO')),
    localizacao VARCHAR(120),
    CHECK (
        (status IN ('RESERVADO', 'VENDIDO') AND encomenda_id IS NOT NULL)
        OR (status IN ('DISPONIVEL', 'EM_ACABAMENTO') AND encomenda_id IS NULL)
    )
);

CREATE TABLE material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL UNIQUE,
    unidade_medida VARCHAR(30) NOT NULL,
    quantidade NUMERIC(12,3) NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
    custo_unitario NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (custo_unitario >= 0),
    estoque_minimo NUMERIC(12,3) NOT NULL DEFAULT 0 CHECK (estoque_minimo >= 0)
);

CREATE TABLE gasto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encomenda_id BIGINT REFERENCES encomenda(id),
    descricao TEXT NOT NULL,
    valor NUMERIC(10,2) NOT NULL CHECK (valor > 0),
    data_gasto DATE NOT NULL,
    categoria VARCHAR(80) NOT NULL
);

CREATE TABLE venda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encomenda_id BIGINT NOT NULL UNIQUE REFERENCES encomenda(id),
    valor_total NUMERIC(10,2) NOT NULL CHECK (valor_total >= 0),
    data_venda TIMESTAMPTZ NOT NULL,
    lucro_bruto NUMERIC(10,2) NOT NULL,
    lucro_liquido_estimado NUMERIC(10,2) NOT NULL
);

CREATE TABLE certificado_artesanal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encomenda_id BIGINT NOT NULL UNIQUE REFERENCES encomenda(id),
    numero_peca VARCHAR(50) NOT NULL UNIQUE,
    data_emissao DATE NOT NULL,
    material_utilizado TEXT,
    texto_certificado TEXT NOT NULL,
    codigo_publico VARCHAR(64) NOT NULL UNIQUE
);

CREATE INDEX idx_encomenda_cliente ON encomenda(cliente_id);
CREATE INDEX idx_encomenda_status ON encomenda(status_encomenda, status_financeiro);
CREATE INDEX idx_item_encomenda_encomenda ON item_encomenda(encomenda_id);
CREATE INDEX idx_pagamento_encomenda ON pagamento(encomenda_id);
CREATE INDEX idx_gasto_data ON gasto(data_gasto);
