CREATE TABLE item_carrinho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL REFERENCES cliente(id) ON DELETE CASCADE,
    modelo_icone_id BIGINT NOT NULL REFERENCES modelo_icone(id),
    quantidade INTEGER NOT NULL CHECK (quantidade BETWEEN 1 AND 99),
    tamanho VARCHAR(20) NOT NULL CHECK (tamanho IN ('PEQUENO','MEDIO','GRANDE','PERSONALIZADO')),
    acabamento VARCHAR(80),
    frase VARCHAR(255),
    nome_familia VARCHAR(120),
    observacoes TEXT,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_item_carrinho_cliente ON item_carrinho(cliente_id);
